# Generated by Django 2.0.5 on 2018-09-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_classification_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='name',
            new_name='title',
        ),
    ]
