# Generated by Django 2.0.5 on 2018-10-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20181001_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生(详细)'},
        ),
    ]
