# Generated by Django 2.0.5 on 2018-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_teacher_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(upload_to='./static/pic', verbose_name='头像'),
        ),
    ]
