# Generated by Django 2.0.5 on 2018-10-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20181001_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': '分类'},
        ),
    ]
