# Generated by Django 2.0.5 on 2018-10-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20181002_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('src', models.ImageField(upload_to='./static/jzx', verbose_name='头像')),
            ],
            options={
                'verbose_name': '照片',
                'db_table': 'imgs',
            },
        ),
        migrations.AlterField(
            model_name='video',
            name='img',
            field=models.ImageField(upload_to='./static/icon', verbose_name='封面'),
        ),
    ]
